Implement getMessages API.
digitalbazaar/bedrock-angular-ldn pull request #1
Opened 2017-02-20 14:29 UTC by mattcollier

@dlongley putting in PR for discussion purposes only.  Please see the FIXME comments in the code.

Another general issue is that we will commonly want to be able to sort messages by date, but presently, the `inboxes` api does not provide an mechanisms for controlling to the sort order of messages contained in the inbox.

Our present use case involves being able to display the last 5-10 messages sent.  How do we want to accomplish this?

2017-02-20 19:36 UTC, davidlehn commented on ldn-service.js
> +    return $http({
$http.get(url, {params: query})

2017-02-20 19:41 UTC, davidlehn commented on ldn-service.js
>        });
`{headers: {'Content-Type', ...}}`

2017-02-21 20:34 UTC, davidlehn commented on ldn-service.js
> +function factory($http, $httpParamSerializer, $q) {
Not using $httpParamSerializer.

2017-02-21 20:41 UTC, dlongley commented on ldn-service.js
>        // TODO: do JSON-LD compaction to CONTEXT_URL
Since we're doing framing below we shouldn't need to do any compaction (framing does this automatically). Can we remove the FIXME and the TODO?

2017-02-21 23:38 UTC, dlongley requested changes

2017-02-21 23:38 UTC, dlongley commented on ldn-service.js
> +        return jsonld.promises.frame(expanded, INBOX_FRAME);
We should try simplifying expand+frame to this non-intuitive workaround:

```js
jsonld.promises.frame(inbox, INBOX_FRAME, {expandContext: {'@base': url}, base: null})
```

2017-02-22 17:04 UTC, mattcollier commented on ldn-service.js
> +        return jsonld.promises.frame(expanded, INBOX_FRAME);
@dlongley where does the value of `url` come from?

2017-02-22 17:45 UTC, mattcollier commented
@dlongley ready for another pass.

2017-02-22 17:50 UTC, dlongley approved these changes

2017-02-22 17:55 UTC, merged